import {
  AtomIcon,
  BookOpenIcon,
  CarIcon,
  ClapperboardIcon,
  CpuIcon,
  DicesIcon,
  EarthIcon,
  Gamepad2Icon,
  LandmarkIcon,
  LightbulbIcon,
  MusicIcon,
  PaletteIcon,
  ScrollIcon,
  ShuffleIcon,
  SigmaIcon,
  TrophyIcon,
  TvIcon,
  VoteIcon,
  type LucideIcon,
} from "lucide-react"

/** An icon for each Open Trivia DB category id (see CATEGORIES in lib/trivia.ts). */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "": ShuffleIcon,
  "9": LightbulbIcon,
  "10": BookOpenIcon,
  "11": ClapperboardIcon,
  "12": MusicIcon,
  "14": TvIcon,
  "15": Gamepad2Icon,
  "16": DicesIcon,
  "17": AtomIcon,
  "18": CpuIcon,
  "19": SigmaIcon,
  "20": LandmarkIcon,
  "21": TrophyIcon,
  "22": EarthIcon,
  "23": ScrollIcon,
  "24": VoteIcon,
  "25": PaletteIcon,
  "28": CarIcon,
}
